DETAIL_BAD_REQUEST = "Invalid request"
DETAIL_UNAUTHORIZED = "Not authenticated"
DETAIL_FORBIDDEN = "Permission denied"
DETAIL_NOT_FOUND = "Resource not found"
DETAIL_METHOD_NOT_ALLOWED = "Method not allowed"
DETAIL_REQUEST_TIMEOUT = "Request timeout"
DETAIL_CONFLICT = "Conflict with current state of the resource"
DETAIL_GONE = "Resource no longer available"
DETAIL_PAYLOAD_TOO_LARGE = "Payload too large"
DETAIL_UNSUPPORTED_MEDIA_TYPE = "Unsupported media type"
DETAIL_UNPROCESSABLE_ENTITY = "Unprocessable entity"
DETAIL_TOO_MANY_REQUESTS = "Too many requests"

DETAIL_INTERNAL_SERVER_ERROR = "An unexpected error occurred. Please try again or contact support."
DETAIL_NOT_IMPLEMENTED = "Not implemented"
DETAIL_BAD_GATEWAY = "Bad gateway"
DETAIL_SERVICE_UNAVAILABLE = "Service unavailable"
DETAIL_GATEWAY_TIMEOUT = "Gateway timeout"

DETAIL_VALIDATION_ERROR = "Invalid request data."
DETAIL_DATABASE_ERROR = "A database error occurred. Please try again later."
DETAIL_UNEXPECTED_ERROR = "An unexpected error occurred. Please try again or contact support."
