VIEWER = "viewer"
INVESTIGATOR = "investigator"
DEPARTMENT_LEAD = "department_lead"
CASE_LEAD = "case_lead"
ADMIN = "admin"

ALL_ROLES = [VIEWER, INVESTIGATOR, DEPARTMENT_LEAD, CASE_LEAD, ADMIN]
INVESTIGATION_ROLES = [INVESTIGATOR, DEPARTMENT_LEAD, CASE_LEAD, ADMIN]

CAN_WRITE = INVESTIGATION_ROLES
CAN_DELETE_OPERATIONAL = INVESTIGATION_ROLES
CAN_DELETE_CASE = [ADMIN]
CAN_UPLOAD = INVESTIGATION_ROLES
CAN_COMMENT = INVESTIGATION_ROLES
# ADMIN_ONLY = [ADMIN]
