ADMIN = "Admin"
OFFICER = "Officer"
ANALYST = "Analyst"
VIEWER = "Viewer"

ALL_ROLES = [ADMIN, OFFICER, ANALYST, VIEWER]

CAN_WRITE = [ADMIN, OFFICER, ANALYST]
CAN_DELETE_OPERATIONAL = [ADMIN, OFFICER]
CAN_DELETE_CASE = [ADMIN]
CAN_UPLOAD = [ADMIN, OFFICER, ANALYST]
CAN_COMMENT = [ADMIN, OFFICER, ANALYST]
ADMIN_ONLY = [ADMIN]
